# Generated by Django 4.1.1 on 2022-10-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roottsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encosta',
            name='prioridadeEncosta',
            field=models.CharField(choices=[('Muito Baixo', 'Muito Baixo'), ('Baixo', 'Baixo'), ('Médio', 'Médio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], default='Muito Baixo', max_length=30),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='coeficienteUmidade',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='declividade',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='numeroConstrucoes',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='proximidadeCorposLiquidos',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='proximidadeRedeViarias',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
