# Generated by Django 4.1.2 on 2022-10-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roottsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_denuncia',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
