# Generated by Django 2.2.8 on 2022-10-21 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roottsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encosta',
            name='localizacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roottsApp.Localizacao'),
        ),
    ]
