# Generated by Django 2.2.8 on 2022-09-30 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roottsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario_denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='encosta',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='local',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='encosta',
            name='nome',
            field=models.CharField(max_length=20),
        ),
    ]
