# Generated by Django 2.2.8 on 2022-10-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roottsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario_denuncia',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='aprovado'),
        ),
    ]
