# Generated by Django 2.2.8 on 2022-09-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roottsApp', '0002_auto_20220930_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario_denuncia',
            name='descricao',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formulario_denuncia',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario_denuncia',
            name='titulo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
